----------------------------------------------------------------
--                                                            --
--                        public.analyses                     --
--                                                            --
----------------------------------------------------------------

drop table if exists analyses;

----------------------------------------------------------------

create table analyses (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  post_id bigint references posts(id) on delete cascade not null,
  user_id uuid references users(id),
  ip inet,
  user_agent text
);

-- Secure the table
alter table analyses enable row level security;

-- Add row-level security
create policy "Public analyses are viewable by everyone." on analyses for select to authenticated, anon using ( true );
create policy "Users can insert analysis." on analyses for insert to authenticated with check ( true );
create policy "Users can update analysis." on analyses for update to authenticated using ( true );
create policy "Users can delete analysis." on analyses for delete to authenticated using ( true );
