----------------------------------------------------------------
--                                                            --
--                        public.analyses                     --
--                                                            --
----------------------------------------------------------------

drop table if exists analyses;

----------------------------------------------------------------

-- Create a table
create table analyses (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  user_id uuid references users(id) on delete cascade not null,
  post_id bigint references posts(id) on delete cascade not null,
  ip inet,
  user_agent text
);

-- Add table indexing
create index analyses_user_id_idx on analyses (user_id);
create index analyses_post_id_idx on analyses (post_id);

-- Secure the table
alter table analyses enable row level security;

-- Add row-level security
create policy "Public access for all users" on analyses for select to authenticated, anon using ( true );
create policy "User can insert analyses" on analyses for insert to authenticated with check ( true );
create policy "User can update analyses" on analyses for update to authenticated using ( true );
create policy "User can delete analyses" on analyses for delete to authenticated using ( true );
