----------------------------------------------------------------
--                                                            --
--                      public.post_tags                      --
--                                                            --
----------------------------------------------------------------

drop table if exists post_tags;

----------------------------------------------------------------

create table post_tags (
  id bigint generated by default as identity primary key,
  post_id bigint references tags(id) on delete cascade not null,
  tag_id bigint references tags(id),
  unique (post_id, tag_id)
);

-- Add table indexing
create index post_tags_post_id_idx on post_tags(post_id, tag_id);

-- Secure the table
alter table post_tags enable row level security;

-- Add row-level security
create policy "Public access for all users" on post_tags for select to authenticated, anon using ( true );
create policy "User can insert post_tags" on post_tags for insert to authenticated with check ( true );
create policy "User can update post_tags" on post_tags for update to authenticated using ( true );
create policy "User can delete post_tags" on post_tags for delete to authenticated using ( true );
