----------------------------------------------------------------
--                                                            --
--                  public.role_permissions                   --
--                                                            --
----------------------------------------------------------------

-- Custom Claims & Role-based Access Control (RBAC)
-- https://supabase.com/docs/guides/auth/custom-claims-and-role-based-access-control-rbac

drop table if exists role_permissions;

----------------------------------------------------------------

-- Create a table
create table role_permissions (
  id bigint generated by default as identity primary key,
  role text not null,
  permission text not null,
  unique (role, permission)
);

-- Secure the table
alter table role_permissions enable row level security;

-- Add row-level security
create policy "Public access for all users" on role_permissions for select to authenticated, anon using ( true );
create policy "User can insert role_permissions" on role_permissions for insert to authenticated with check ( true );
create policy "User can update role_permissions" on role_permissions for update to authenticated using ( true );
create policy "User can delete role_permissions" on role_permissions for delete to authenticated using ( true );
