----------------------------------------------------------------
--                                                            --
--                     public.user_plans                      --
--                                                            --
----------------------------------------------------------------

-- Custom Claims & Role-based Access Control (RBAC)
-- https://supabase.com/docs/guides/auth/custom-claims-and-role-based-access-control-rbac

drop trigger if exists on_updated_at on user_plans;

drop table if exists user_plans;

----------------------------------------------------------------

-- drop type if exists public.user_plan;
-- create type public.user_plan as enum ('free', 'basic', 'standard', 'premium');
-- alter type public.type_name add value 'new_type';
-- alter type public.type_name rename value 'old_type' to 'new_type';
-- alter type public.type_name rename to new_type_name;

----------------------------------------------------------------

create table user_plans (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  user_id uuid references users(id) on delete cascade not null,
  plan text default 'free'::text not null,
  unique (user_id, plan)
);
comment on column user_plans.plan is 'free, basic, standard, premium';

-- Secure the table
alter table user_plans enable row level security;

-- Add row-level security
create policy "Public access for all users" on user_plans for select to authenticated, anon using ( true );
create policy "User can insert their own user_plans" on user_plans for insert to authenticated with check ( (select auth.uid()) = user_id );
create policy "User can update their own user_plans" on user_plans for update to authenticated using ( (select auth.uid()) = user_id );
create policy "User can delete their own user_plans" on user_plans for delete to authenticated using ( (select auth.uid()) = user_id );

-- Functions for tracking last modification time
create extension if not exists moddatetime schema extensions;
create trigger on_updated_at before update on user_plans
  for each row execute procedure moddatetime (updated_at);
