-- SQL Editor > New query

drop table if exists analyses;

create table analyses (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now() not null,
  post_id bigint references posts(id) on delete cascade not null,
  user_id uuid references users(id),
  ip inet,
  user_agent text
);
