-- SQL Editor > New query

drop function if exists set_view_count;
drop function if exists set_post_meta;

drop table if exists post_metas;

create table post_metas (
  id bigint generated by default as identity primary key,
  post_id bigint references posts(id) on delete cascade not null,
  meta_key varchar(255),
  meta_value text,
  unique (post_id, meta_key)
);

-- Secure the table
alter table post_metas enable row level security;

-- Add row-level security
create policy "Public post_metas are viewable by everyone." on post_metas for select to authenticated, anon using ( true );
create policy "Users can insert post_meta." on post_metas for insert to authenticated with check ( true );
create policy "Users can update post_meta." on post_metas for update to authenticated using ( true );
create policy "Users can delete post_meta." on post_metas for delete to authenticated using ( true );

-- const { data, error } = await supabase.rpc('set_post_meta', { pid: '', metakey: '', metavalue: '' });
-- select * from set_post_meta('pid', 'metakey', 'metavalue');

create or replace function set_post_meta(pid bigint, metakey text, metavalue text)
returns void
security definer set search_path = public
as $$
begin
  if exists (select 1 from post_metas where post_id = pid and meta_key = metakey) then
    update post_metas set meta_value = metavalue where post_id = pid and meta_key = metakey;
  else
    insert into post_metas(post_id, meta_key, meta_value) values(pid, metakey, metavalue);
  end if;
end;
$$ language plpgsql;

-- const { data, error } = await supabase.rpc('set_view_count', { pid: 0 });
-- select * from set_view_count('pid');

create or replace function set_view_count(pid bigint)
returns void
security definer set search_path = public
as $$
begin
  if exists (select 1 from post_metas where post_id = pid and meta_key = 'view_count') then
    update post_metas set meta_value = meta_value::integer + 1 where post_id = pid and meta_key = 'view_count';
  else
    insert into post_metas(post_id, meta_key, meta_value) values(pid, 'view_count', '1');
  end if;
end;
$$ language plpgsql;
