-- Custom Claims & Role-based Access Control (RBAC)
-- https://supabase.com/docs/guides/auth/custom-claims-and-role-based-access-control-rbac

drop table if exists role_permissions;

create table role_permissions (
  id bigint generated by default as identity primary key,
  role text not null,
  permission text not null,
  unique (role, permission)
);

alter table role_permissions enable row level security;

create policy "Public role_permissions are viewable by everyone." on role_permissions for select to authenticated, anon using ( true );
create policy "Users can insert role_permission." on role_permissions for insert to authenticated with check ( true );
create policy "Users can update role_permission." on role_permissions for update to authenticated using ( true );
create policy "Users can delete role_permission." on role_permissions for delete to authenticated using ( true );
