import * as React from 'react'
import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import { Analytics } from '@/components/analytics'

import { lng } from '@/i18next.config'
import { I18nextProvider } from '@/context/i18next-provider'

import { cn } from '@/utils/tailwind'
import { ThemeProvider } from '@/context/theme-provider'
import { Toaster } from '@/components/ui/sonner'
import { TailwindIndicator } from '@/components/tailwind-indicator'

import './globals.css'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang={lng} suppressHydrationWarning>
      <body className={cn('font-sans antialiased', fontSans.variable)}>
        <I18nextProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div id="__next">{children}</div>
            <Toaster richColors closeButton />
            <TailwindIndicator />
          </ThemeProvider>
        </I18nextProvider>
        <Analytics />
      </body>
    </html>
  )
}
